### ISSUE TITLE
Null pipewire default metadata property update causes crash

### ISSUE THREAD

**Issue by pterror** [quickshell-mirror/quickshell#6]
### General crash information

<details> <summary>General information</summary>

```
===== Quickshell Crash =====
Git Revision: 3ed39b2a798419a168e5c79a2db9f7ee20de70fa
Crashed process ID: 5835
Run ID: es1lbrvks

===== Shell Information =====
Shell ID: 0d7462767e912211f753440325c363fb
Config Path: /home/me/.config/quickshell/shell.qml

===== Report Integrity =====
Minidump save status: 0
Log save status: 0

===== System Information =====
Qt Version: 6.7.2

/etc/os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241004.bc947f5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

/etc/lsb-release:
DISTRIB_CODENAME=vicuna
DISTRIB_DESCRIPTION="NixOS 24.11 (Vicuna)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="24.11"
LSB_VERSION="24.11 (Vicuna)"
```

</details>

### What caused the crash

i opened firefox

### Minidump

github says "we don't support that file type" can you pre-compress it plz thanks fox

[minidump.zip](https://github.com/user-attachments/files/17265977/minidump.zip)

### Log file

same here .qslog is not supported

[log.zip](https://github.com/user-attachments/files/17265979/log.zip)

### Configuration

https://github.com/pterror/config-quickshell

current status locally is green on `master` so there should be no differences on my local config

### Backtrace

<details> <summary>Full backtrace</summary>

```asm
(gdb) bt -full
#0  0x00007bb92637202b in __strcmp_avx2 () at /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#1  0x0000648c68d353d1 in qs::service::pipewire::PwDefaultTracker::onMetadataProperty(char const*, char const*, char const*) ()
#2  0x00007bb9269eb170 in void doActivate<false>(QObject*, int, void**) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#3  0x0000648c68d0fcdb in qs::service::pipewire::PwMetadata::propertyChanged(char const*, char const*, char const*) ()
#4  0x0000648c68d2ca55 in qs::service::pipewire::PwMetadata::onProperty(void*, unsigned int, char const*, char const*, char const*) ()
#5  0x00007bb918e3a90c in metadata_proxy_demarshal_property ()
    at /nix/store/fm8lwmakyhk770r9vc6db4bf68mcm88g-pipewire-1.2.3/lib/pipewire-0.3/libpipewire-module-metadata.so
#6  0x00007bb918bbd36d in process_remote ()
    at /nix/store/fm8lwmakyhk770r9vc6db4bf68mcm88g-pipewire-1.2.3/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#7  0x00007bb918bbdb90 in on_remote_data ()
    at /nix/store/fm8lwmakyhk770r9vc6db4bf68mcm88g-pipewire-1.2.3/lib/pipewire-0.3/libpipewire-module-protocol-native.so
#8  0x00007bb91a12f9f6 in loop_iterate ()
    at /nix/store/fm8lwmakyhk770r9vc6db4bf68mcm88g-pipewire-1.2.3/lib/spa-0.2/support/libspa-support.so
#9  0x0000648c68d1e5ab in qs::service::pipewire::PwCore::poll() ()
#10 0x00007bb9269eb170 in void doActivate<false>(QObject*, int, void**) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#11 0x00007bb9269f87bf in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) () at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#12 0x00007bb9269f9035 in QSocketNotifier::event(QEvent*) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#13 0x00007bb926985a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#14 0x00007bb926c6453c in socketNotifierSourceDispatch(_GSource*, int (*)(void*), void*) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#15 0x00007bb925d0e0a4 in g_main_dispatch ()
    at /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
#16 0x00007bb925d112c7 in g_main_context_iterate_unlocked.isra ()
    at /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
#17 0x00007bb925d118ec in g_main_context_iteration ()
    at /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
#18 0x00007bb926c6347c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#19 0x00007bb926992d33 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#20 0x00007bb92698eb96 in QCoreApplication::exec() ()
    at /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
#21 0x0000648c68bd05b3 in qs::launch::launch(qs::launch::LaunchArgs const&, char**, QCoreApplication*) ()
#22 0x0000648c68bcc10e in qs::launch::launchFromCommand(qs::launch::CommandState&, QCoreApplication*) ()
#23 0x0000648c68bc8031 in qs::launch::runCommand(int, char**, QCoreApplication*) ()
#24 0x0000648c68bc484f in qs::launch::main(int, char**) ()
#25 0x00007bb92623314e in __libc_start_call_main ()
    at /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#26 0x00007bb926233209 in __libc_start_main_impl ()
    at /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
#27 0x0000648c68bae265 in _start ()
```
</details>

**Comment by outfoxxed** [comment]
Apparently firefox thinks its a good idea to send a metadata update with both null keys and values? Easy fix but that's weird.

**Comment by outfoxxed** [comment]
Appears github won't auto close issues when pushed by the push mirror.

As for the file names, that's annoying. Fortunately github doesn't check file contents so I'll just add .txt to the end of the file names or something. Weird that you can upload zips but not arbitrary extensions.
