### ISSUE TITLE
Crash on startup after upgrading Hyprland and Quickshell(?)

### ISSUE THREAD

**Issue by nonetrix** [quickshell-mirror/quickshell#7]
### General crash information

<details> <summary>General information</summary>

```
===== Quickshell Crash =====
Git Revision: 8e40112d143f805a3fdcc967c50500e2c035ff12
Crashed process ID: 17574
Run ID: pjdd1efls

===== Shell Information =====
Shell ID: 9811d2b978007516251a3f5b811b4607
Config Path: /home/noah/.config/quickshell/shell.qml

===== Report Integrity =====
Minidump save status: 0
Log save status: 0

===== System Information =====
Qt Version: 6.7.3

/etc/os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

/etc/lsb-release:
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
```

</details>

### What caused the crash

Upgrading either Hyprland or Quickshell caused it, outside of that not sure

### Minidump

[minidump.dmp.txt](https://github.com/user-attachments/files/17388077/minidump.dmp.txt)

### Log file

[info.txt](https://github.com/user-attachments/files/17388076/info.txt)

### Configuration

[quickshell.tar.gz](https://github.com/user-attachments/files/17388075/quickshell.tar.gz)

### Backtrace

```
#0  0x00007ad18b3e2d90 in QDebug::operator<< (this=0x7ffc36421ab8, t=...) at /usr/include/qt6/QtCore/qdebug.h:127
No locals.
#1  0x00007ad18b3dc041 in QtWaylandClient::QWaylandShellSurface::setXdgActivationToken (this=<optimized out>, token=...) at /usr/src/debug/qt6-wayland/qtwayland/src/client/qwaylandshellsurface.cpp:75
        qt_category = <optimized out>
#2  0x000060b12ea21951 in ?? ()
No symbol table info available.
#3  0x000060b12ea2a50b in ?? ()
No symbol table info available.
#4  0x000060b12ea28ab3 in ?? ()
No symbol table info available.
#5  0x000060b12ea28ab3 in ?? ()
No symbol table info available.
#6  0x000060b12ea29224 in ?? ()
No symbol table info available.
#7  0x000060b12ea28ab3 in ?? ()
No symbol table info available.
#8  0x000060b12ea2a5f6 in ?? ()
No symbol table info available.
#9  0x000060b12ea28ab3 in ?? ()
No symbol table info available.
#10 0x000060b12ea2a5f6 in ?? ()
No symbol table info available.
#11 0x000060b12ea28ab3 in ?? ()
No symbol table info available.
#12 0x000060b12ea2ba53 in ?? ()
No symbol table info available.
#13 0x000060b12ea1e3d3 in ?? ()
No symbol table info available.
#14 0x000060b12ea1345d in ?? ()
No symbol table info available.
#15 0x000060b12e9c2d27 in ?? ()
No symbol table info available.
#16 0x00007ad188634e08 in __libc_start_call_main (main=main@entry=0x60b12e9c2c90, argc=argc@entry=1, argv=argv@entry=0x7ffc36422e48) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140721218793032, -6003461034939583361, 1, 0, 135040406003712, 106314109697368, -6003461034958457729, -6416477464998382465}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x7ad18b6e2000 <_rtld_global>}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#17 0x00007ad188634ecc in __libc_start_main_impl (main=0x60b12e9c2c90, argc=1, argv=0x7ffc36422e48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc36422e38)
    at ../csu/libc-start.c:360
No locals.
#18 0x000060b12e9c4825 in ?? ()
No symbol table info available.
```

**Comment by outfoxxed** [comment]
Was this installed via the AUR or a manual build? There should be more debug information if it was the AUR.

Unfortunately I can't reconstruct traces from minidumps on arch without the original binary or debuginfo file. Can you send the binary?

I also can't reproduce the crash locally. If you can reliably reproduce it, please compile with debuginfo and send a trace with it.

**Comment by nonetrix** [comment]
Is this what you mean? Just rename it, idk why Github limits what file extensions I can upload. But, it is from the AUR
[quickshell.txt](https://github.com/user-attachments/files/17388649/quickshell.txt)

**Comment by outfoxxed** [comment]
Did you strip it? Is your AUR helper stripping it?

**Comment by outfoxxed** [comment]
looks like its a makepkg default behavior. Sorry, but can you compile manually by running

```
$ QTWAYLANDSCANNER="/usr/lib/qt6/qtwaylandscanner" cmake -GNinja -B build -DCMAKE_BUILD_TYPE="RelWithDebInfo"
$ cmake --build build
```

and send the binary? (looking into a way to fix the aur package but that won't happen for a bit)

**Comment by nonetrix** [comment]
It seems to work after manually building it, but there also isn't a -git package in the AUR, I shouldn't have assumed I was running -git version that doesn't exist sorry

**Comment by outfoxxed** [comment]
It is a git package, there's no stable release yet. That's still helpful though. Your qt version probably changed to one that isn't binary compatible with the APIs we use. I'll add that information to the crash reporter.

**Comment by nonetrix** [comment]
Forcing rebuild seemed to have fixed the AUR package, is no way to make it automatically do this when QT is updated or something?

**Comment by outfoxxed** [comment]
unsure, I'll ask the aur packager
