### ISSUE TITLE
quickshell non-fatal crash with nvidia and nvk

### ISSUE THREAD

**Issue by pterror** [quickshell-mirror/quickshell#9]
### General crash information

<details> <summary>General information</summary>

```
===== Build Information =====
Git Revision: 3fc1c914c7946f139b22006a6c554cce9ecc1064
Buildtime Qt Version: 6.8.0
Build Type: RelWithDebInfo
Compiler: Clang (18.1.8)
Complie Flags: 

Build configuration:
  Distributor: Official-Nix-Flake
  Distributor provided debuginfo: TRUE
  Disable precompild headers (dev): OFF
  Build tests (dev): OFF
  ASAN (dev): OFF
  Keep Frame Pointers (dev): OFF
  Crash Handling: TRUE
  Use jemalloc: TRUE
  Unix Sockets: ON
  Wayland: TRUE
    Wlroots Layer-Shell: ON
    Session Lock: ON
    Foreign Toplevel Management: ON
    Hyprland: TRUE
      Hyprland IPC: ON
      Hyprland Global Shortcuts: ON
      Hyprland Focus Grabbing: ON
    I3/Sway: TRUE
      I3/Sway IPC: ON
  X11: ON
  System Tray: ON
  PipeWire: TRUE
  Mpris: ON
  Pam: TRUE
  Greetd: ON
  UPower: ON
  Notifications: ON

===== Runtime Information =====
Runtime Qt Version: 6.8.0
Crashed process ID: 561324
Run ID: sjzbavrgos
Shell ID: 0d7462767e912211f753440325c363fb
Config Path: /home/me/.config/quickshell/shell.qml

===== Report Integrity =====
Minidump save status: 0
Log save status: 0
Binary copy status: 0

===== System Information =====

/etc/os-release:
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20241209.a73246e"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"

/etc/lsb-release:
DISTRIB_CODENAME=warbler
DISTRIB_DESCRIPTION="NixOS 25.05 (Warbler)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="25.05"
LSB_VERSION="25.05 (Warbler)"
```

</details>

### What caused the crash

i dunno :sob

### Minidump

[minidump.dmp.log](https://github.com/user-attachments/files/18134037/minidump.dmp.log)

### Log file

[log.qslog.log](https://github.com/user-attachments/files/18134039/log.qslog.log)

### Configuration

<https://github.com/pterror/config-quickshell>

### Backtrace

<details>
<summary>full backtrace</summary>

```
#0  0x00007279ffc774c4 in pushbuf_dump ()
   from /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
(gdb) bt -full
#0  0x00007279ffc774c4 in pushbuf_dump ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#1  0x00007279ffc79a97 in pushbuf_flush.isra ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#2  0x00007279ffc7a3b9 in nouveau_pushbuf_kick ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#3  0x0000727a0025c95e in nvc0_draw_vbo ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#4  0x00007279ff55064b in _mesa_validated_drawrangeelements ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#5  0x00007279ff551a79 in _mesa_DrawElementsBaseVertex ()
    at /nix/store/w02n42gkvqb13xk8vvyn4pb58dpv39xx-mesa-24.2.6/lib/libgallium-24.2.6.so
#6  0x0000727a20fd003e in QRhiGles2::executeCommandBuffer(QRhiCommandBuffer*) ()
    at /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0/lib/libQt6Gui.so.6
#7  0x0000727a20fd106f in QRhiGles2::endFrame(QRhiSwapChain*, QFlags<QRhi::EndFrameFlag>) ()
    at /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0/lib/libQt6Gui.so.6
#8  0x0000727a20e4d1ec in QRhi::endFrame(QRhiSwapChain*, QFlags<QRhi::EndFrameFlag>) ()
    at /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0/lib/libQt6Gui.so.6
#9  0x0000727a21af63eb in QSGRenderThread::syncAndRender() ()
    at /nix/store/x3fzgdyyw2k4q8bj3qsrjy7jsdk0lwgl-qtdeclarative-6.8.0/lib/libQt6Quick.so.6
#10 0x0000727a21af975b in QSGRenderThread::run() ()
    at /nix/store/x3fzgdyyw2k4q8bj3qsrjy7jsdk0lwgl-qtdeclarative-6.8.0/lib/libQt6Quick.so.6
#11 0x0000727a1f94eae4 in QThreadPrivate::start(void*) ()
    at /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0/lib/libQt6Core.so.6
#12 0x0000727a1f097d02 in start_thread ()
    at /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
#13 0x0000727a1f1173ac in __clone3 ()
    at /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
```
</details>

**Comment by outfoxxed** [comment]
I can't really do much with this one. Is it reproducible?

**Comment by outfoxxed** [comment]
Closing unless you can provide more info.
